services:
  monitor:
    image: l6eai/l6e-forge-monitor:latest
    ports:
      - "8321:8321"
            
  api:
    image: l6eai/l6e-forge-api:latest
    environment:
      - AF_MONITOR_URL=http://monitor:8321
      - AF_WORKSPACE=/workspace
      - OLLAMA_HOST=http://host.docker.internal:11434
      - LMSTUDIO_HOST=http://host.docker.internal:1234/v1
      - AF_MEMORY_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - AF_MEMORY_COLLECTION=agent_memory
    ports:
      - "8000:8000"
            
  ui:
    image: l6eai/l6e-forge-ui:latest
    
    ports:
      - "5173:5173"
            
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
            
