
services:
  monitor:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.monitor
    ports:
      - "8321:8321"
    volumes:
      - ./l6e_forge:/app/l6e_forge
    environment:
      - MONITOR_PORT=8321
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    environment:
      - AF_MONITOR_URL=http://monitor:8321
      - AF_WORKSPACE=/workspace
    volumes:
      - ./l6e_forge:/app/l6e_forge
      - ./tmp-workspace:/workspace
    depends_on:
      - monitor
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.ui
    ports:
      - "5173:5173"
    environment:
      - VITE_MONITOR_URL=http://monitor:8321
      - VITE_API_URL=http://api:8000
    volumes:
      - .:/app
    depends_on:
      - api
