# This compose file has been modified to allow testing the dev experience with hot-reloads in the main l6eai/l6e-forge repository

# Do not use this as an example of how to run forge in your environment (it differs from the template generated compose file)

services:
  monitor:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.monitor
    volumes:
      - ../../l6e_forge/monitor:/app/l6e_forge/monitor
    ports:
      - "8321:8321"
            
  api:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.api
    environment:
      # Do not set AF_MONITOR_URL so API serves monitor endpoints locally
      - AF_MONITOR_URL=http://monitor:8321
      - AF_WORKSPACE=/workspace
      - OLLAMA_HOST=http://host.docker.internal:11434
      - LMSTUDIO_HOST=http://host.docker.internal:1234/v1
      - AF_MEMORY_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - AF_MEMORY_COLLECTION=agent_memory
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
            
  ui:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.ui
    volumes:
      - ../../site/agent-ui:/app/static/ui
    environment:
      - VITE_API_BASE=/api
      - VITE_MONITOR_BASE=/monitor
      - VITE_PROXY_API_TARGET=http://api:8000
    ports:
      - "5173:5173"
            
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
