services:
  monitor:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile.monitor
    environment:
      - MONITOR_PORT=8321
    ports:
      - "8321:8321"

  api:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile.api
    environment:
      - AF_MONITOR_URL=http://monitor:8321
      - AF_WORKSPACE=/workspace
    volumes:
      - ./example-workspace:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - monitor

  ui:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile.ui
    environment:
      - VITE_MONITOR_URL=http://monitor:8321
      - VITE_API_URL=http://api:8000
    ports:
      - "5173:5173"
    volumes:
      - ..:/app
    depends_on:
      - api
