[agent]
name = "test-demo"
version = "0.1.0"
[model]
provider = "ollama"
model = "gpt-oss:120b"

[model.auto]
enabled = true
providers = ["ollama"]
quality = "balanced"
[memory]
embedding_model = "nomic-embed-text:latest"
